# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

let
  uuids = {
    root = "f8633210-5807-49eb-a2e4-a18d47b20dd2";
    boot = "FEF6-1FE8";
    home = "4fc8a774-3b74-4969-87c7-cae44dde8ff7";
    swap = "9eb2259b-6399-4bfd-af3e-c0d9a71dadfe";
  };

  mkBtrfs = subvol: {
    device = "/dev/disk/by-uuid/${uuids.root}";
    fsType = "btrfs";
    options = [ "subvol=${subvol}" ];
  };
in
{ }
|> (_: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
})
|> (
  attrs:
  attrs
  // {
    boot = {
      initrd.availableKernelModules = [
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      initrd.kernelModules = [ ];
      kernelModules = [ "kvm-amd" ];
      extraModulePackages = [ ];
    };
  }
)
|> (
  attrs:
  attrs
  // {
    fileSystems = {
      "/" = mkBtrfs "@";
      "/nix" = mkBtrfs "@nix";
      "/var/log" = mkBtrfs "@log";
      "/boot" = {
        device = "/dev/disk/by-uuid/${uuids.boot}";
        fsType = "vfat";
        options = [
          "fmask=0022"
          "dmask=0022"
        ];
      };
      "/home" = mkBtrfs "@home" // {
        neededForBoot = true;
      };
    };
  }
)
|> (
  attrs:
  attrs
  // {
    swapDevices = [
      { device = "/dev/disk/by-uuid/${uuids.swap}"; }
    ];
  }
)
|> (
  attrs:
  attrs
  // {
    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  }
)
