# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f8633210-5807-49eb-a2e4-a18d47b20dd2";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/f8633210-5807-49eb-a2e4-a18d47b20dd2";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/f8633210-5807-49eb-a2e4-a18d47b20dd2";
    fsType = "btrfs";
    options = [ "subvol=@log" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FEF6-1FE8";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/4fc8a774-3b74-4969-87c7-cae44dde8ff7";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/9eb2259b-6399-4bfd-af3e-c0d9a71dadfe"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
