[shorturls]
gh = "github:{path}"
manic = "github:manic-systems/{path}"

[all_follow]
nixpkgs = ["stable", "nixpkgs", "master"]
fenix = "fenix"
rust-overlay = "rust-overlay"
niri-src = ["niri-stable", "niri-unstable"]
nix = "nix-src"
crane = "crane"
git-hooks = ["git-hooks-nix"]
nixpkgs-lib = "nixpkgs-lib"
rust-analyzer-src = "rust-analyzer"
xwayland-satellite = [
  "xwayland-satellite-stable",
  "xwayland-satellite-unstable",
]
hjem-rum = "hjem"

[inputs.rust-overlay]
url = "gh:oxalica/rust-overlay"

# core toolchain --------------------------------------------------------------

[inputs.nixpkgs]
url = "gh:nixos/nixpkgs/nixos-unstable"

[inputs.master]
url = "gh:nixos/nixpkgs/master"

[inputs.fenix]
url = "gh:nix-community/fenix"
# secrets / identity ----------------------------------------------------------

[inputs.agenix]
url = "gh:ryantm/agenix"

# build / system --------------------------------------------------------------

[inputs.nixos-core]
url = "github:llakala/nixos-core"

[inputs.nix-wrappers]
url = "gh:midischwarz12/nix-wrappers"

[inputs.nix-src]
url = "gh:NixOS/nix"

# build / tooling -------------------------------------------------------------

[inputs.tack]
url = "manic:tack/next"

[inputs.cade]
url = "manic:cade"

# misc personal flakes --------------------------------------------------------

[inputs.spicetify]
url = "gh:Gerg-L/spicetify-nix"

# niri / desktop --------------------------------------------------------------

[inputs.niri-src]
url = "gh:YaLTeR/niri"

[inputs.noctalia-shell]
url = "gh:noctalia-dev/noctalia-shell/legacy-v4"

[inputs.tuigreet]
url = "gh:notashelf/tuigreet"

[inputs.watt]
url = "gh:notashelf/watt"

# system services -------------------------------------------------------------

[inputs.qtengine]
url = "gh:kossLAN/qtengine"

[inputs.quickshell]
url = "git+https://git.outfoxxed.me/quickshell/quickshell.git"

[inputs.hjem-impure]
url = "github:Rexcrazy804/hjem-impure"

[inputs.hjem]
url = "github:feel-co/hjem"

[inputs.niri-nix]
url = "git+https://codeberg.org/BANanaD3V/niri-nix.git"

[inputs.sysc-greet]
url = "github:kagurazakei/sysc-greet/master"
follow = { nixpkgs = "nixpkgs", hyprland = "hyprland", niri-nix = "niri-nix" }

[inputs.ambxst]
url = "github:kagurazakei/ambxst"

[inputs.viu]
url = "gh:viu-media/viu"

[inputs.neovim-nightly]
url = "gh:nix-community/neovim-nightly-overlay"

[inputs.catp-bat]
url = "gh:catppuccin/bat"

[inputs.chaotic]
url = "gh:chaotic-cx/nyx/nyxpkgs-unstable"

[inputs.flake-utils]
url = "gh:numtide/flake-utils"

[inputs.impermanence]
url = "gh:nix-community/impermanence"

[inputs.mango]
url = "gh:mangowm/mango"

[inputs.mnw]
url = "gh:Gerg-L/mnw"

[inputs.nix-cachyos-kernel]
url = "gh:xddxdd/nix-cachyos-kernel"

[inputs.nix-flatpak]
url = "gh:gmodena/nix-flatpak"

[inputs.nix-index-database]
url = "gh:nix-community/nix-index-database"

[inputs.nixos-hardware]
url = "gh:Nixos/nixos-hardware"

[inputs.rosep-fish]
url = "gh:rose-pine/fish"

[inputs.shizuruPkgs]
url = "gh:kagurazakei/shizuruPkgs"

[inputs.stash]
url = "gh:NotAShelf/stash"

[inputs.waifu-cursors]
url = "gh:kagurazakei/waifu-cursors"

[inputs.rosep-kitty]
url = "gh:rose-pine/kitty"
type = "fetch"

[inputs.rosep-foot]
url = "gh:rose-pine/foot"
type = "fetch"

[inputs.hyprview]
url = "github:kagurazakei/quickshell-overview"
type = "fetch"

[inputs.npins]
url = "gh:andir/npins"
type = "fetch"

[inputs.cat-gtk-themes]
url = "gh:kagurazakei/cat-gtk-themes"
type = "fetch"

[inputs.hjem-rum]
url = "github:snugnug/hjem-rum"

[inputs.walls]
url = "git+https://github.com/kagurazakei/walls.git"
type = "fetch"

[inputs.noctalia-greeter]
url = "git+https://github.com/noctalia-dev/noctalia-greeter.git"

[inputs.noctalia]
url = "gh:noctalia-dev/noctalia-shell"

[inputs.equibop]
url = "gh:Equicord/Equibop"
type = "fetch"

[inputs.nixos-stable]
url = "https://channels.nixos.org/nixos-26.05/nixexprs.tar.xz"

[inputs.helium]
url = "https://github.com/imputnet/helium-linux/releases/download/0.13.3.1/helium-0.13.3.1-arm64_linux.tar.xz"
type = "fetch"
