animations=1
layer_animations=1
animation_type_open=slide
animation_type_close=slide
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=0
zoom_initial_ratio=0.6
zoom_end_ratio=0.9
fadein_begin_opacity=0.2
fadeout_begin_opacity=0.85
animation_duration_move=600
animation_duration_open=800
animation_duration_tag=650
animation_duration_close=500
animation_duration_focus=600
animation_curve_open=0.18,0.89,0.32,1.28
animation_curve_move=0.34,1.56,0.64,1.0
animation_curve_tag=0.23,1.0,0.32,1.0
animation_curve_close=0.18,0.89,0.32,1.28
animation_curve_focus=0.23,1.0,0.32,1.0
animation_curve_opafadein=0.4,0.0,0.2,1.0
animation_curve_opafadeout=0.4,0.0,0.2,1.0
