animations=1
layer_animations=1
animation_type_open=zoom
animation_type_close=zoom
layer_open_animation_type=zoom
layer_close_animation_type=zoom
animation_fade_in=1
animation_fade_out=1
fadein_begin_opacity=0.5
fadeout_begin_opacity=0.45
tag_animation_direction=0
animation_duration_tag=450
zoom_initial_ratio=0.6
zoom_end_ratio=1.0
animation_duration_move=500
animation_duration_open=450
animation_duration_close=350
animation_duration_focus=600
animation_curve_open=0.72,1.00,0.68,1.0
animation_curve_move=0.70,1.0,0.65,1.0
animation_curve_tag=0.7,0.7,0.65,1.0
animation_curve_close=0.85,1.0,0.65,1.0
animation_curve_focus=0.0,0.55,0.45,1.0
animation_curve_opafadein=0.6,0.55,0.65,1.0
animation_curve_opafadeout=0.85,1.0,0.65,1.0
