# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x181b2aff
rootcolor = 0x1f2335ff
bordercolor = 0x626a9eff
dropcolor = 0x7a88cf80
splitcolor = 0x9cd58aff
focuscolor=0xeb6f92dd
maximizescreencolor = 0xd7729fff
urgentcolor = 0xf7768eff
scratchpadcolor = 0x9cd58aff
globalcolor = 0x1d2c7aff
overlaycolor = 0x811645ff
