[mgr]
prepend_keymap = [
  { on = ["!"], run = 'shell "$SHELL" --block', desc = "Open shell here" },
  { on = "<C-u>", run = "seek -5", desc = "Seek up 5 units" },
  { on = "<C-d>", run = "seek 5", desc = "Seek down 5 units" },
  { on = "K", run = "arrow -50%", desc = "Move up half page" },
  { on = "J", run = "arrow 50%", desc = "Move down half page" },
  { on = "<A-k>", run = "arrow -5", desc = "Move up 5 lines" },
  { on = "<A-j>", run = "arrow 5", desc = "Move down 5 lines" },
  { on = ["s"], run = "plugin searchjump --autocd", desc = "Flash search" },
  { on = "S", run = "search --via=fd", desc = "Search with fd" },

  # Clipboard
  { on = ["<C-y>"], run = 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', desc = "Copy paths" },

  # Create
  { on = "A", run = "create --dir", desc = "Create dir" },
  { on = ["c", "a"], run = "plugin ouch", desc = "Archive" },

  # Git
  { on = ["g", "r"], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Git root" },

  # Tabs
  { on = "H", run = "tab_switch -1 --relative", desc = "Prev tab" },
  { on = "L", run = "tab_switch 1 --relative", desc = "Next tab" },
  { on = "<", run = "tab_swap -1", desc = "Swap prev" },
  { on = ">", run = "tab_swap 1", desc = "Swap next" },

  # Plugins
  { on = "M", run = "plugin mount", desc = "Mount manager (USB)" },
]

append_keymap = [
  { on = ["e"], run = "open", desc = "Open" },
  { on = ["E"], run = "open --interactive", desc = "Open interactive" },
]

[completion]
prepend_keymap = [
  { on = "<C-k>", run = "arrow -1", desc = "Up" },
  { on = "<C-j>", run = "arrow 1", desc = "Down" },
]
